### ISSUE TITLE
built-in dapp browser

### ISSUE THREAD

**Issue by mikelam1988** [krakenfx/wallet#14]
I hope the wallet can have a built-in dapp browser

**Comment by shaung86** [comment]
Thanks Mikelam1988. We hear you and have an exciting roadmap ahead! Stay tuned for future releases.

**Comment by diyism** [comment]
Indeed, intent-jumping from the mobile browser to the wallet app for signing transactions is too slow (due to app launch time + WalletConnect network time).

It is essential for Kraken Wallet to include a built-in browser. It would be even better if transaction data could be passed directly to the kraken wallet from the built-in browser through Deep Linking or similar methods, without relying on the network.

It seems that Kraken Wallet is currently the only open-source Android wallet that supports transaction preview (making pending transactions human-readable).
